# Configuration for Prevent-Public-Repos
# Turn on Monitor Mode. In this mode the repo visibility is not modified and only an Issue is created
monitorOnly: false
# Enables detection of repos that change visibility from private to public (not just newly created ones)
enablePrivateToPublic: false
# Issue Title when repo is privatized
privatizedIssueTitle: '[CRITICAL] Public Repositories are Disabled for FR Project'
# Issue Body when repo is privatized
privatizedIssueBody: 'NOTE: Public Repos are prohibited for FR Project! Repository was automatically converted to a Private Repo.'
# Issue Title when monitor mode is enabled
monitorIssueTitle: '[CRITICAL] GitHub Public Repository Created'
# Issue Body when monitor mode is enable
monitorIssueBody: 'Please note that this repository is publicly visible to the internet!'
# Users/Groups that should be cc'ed on the issue. Should be users/groups separated by a space.
# ccList: '@acn-ryota-saito @acn-ryota-saito'
# Repos to exclude in detection. Should be a List of Strings.
# excludeRepos: ['repo1', 'repo2']
